name: Jekyll test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Build site
      run: jekyll build
    - name: HTMLProofer tests
      run: bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external --checks_to_ignore LinkCheck  
